import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync(process.argv[2] || new URL('./plugin.js',import.meta.url),'utf8');
const helpers=source.slice(source.indexOf('function botsModIsInternalSession'),source.indexOf('import{CHAT_EMPTY_AREA'));
const render=source.slice(source.indexOf('function hc('),source.indexOf('function yc('));
let show=false, archiveRows, rows=[{id:'internal',title:'Bot Chat'},{id:'user',title:'User task'}];
const jsx=(type,props)=>({type,...props});
const atom={get:()=>show,set:v=>{show=v}};
const hidden={};const hiddenAtom={get:()=>hidden};
const ctx={botsModShowInternal:atom,botsModShelfValue:a=>a.get(),botsModHiddenBots:hiddenAtom,botsModHiddenName:b=>`${b?.connectionId||'local'}::${b?.name||'default'}`,botsModSetHidden:(b,hide)=>{const k=`${b?.connectionId||'local'}::${b?.name||'default'}`;hide?hidden[k]={name:b.name,connectionId:b.connectionId,at:Date.now()}:delete hidden[k];},G:jsx,Wi:"tooltip",At:"icon",botsModCompactCss:'',window:{},botsModInternalUseState:()=>[show,f=>{show=f(show)}],fc:()=>({t:{sidebar:{row:{}},common:{}}}),te:()=>({bot:{},roster:{}}),rc:()=>({data:rows}),oc:x=>x,j:()=>({}),Xt:a=>a===atom?show:{},B:{},fo:()=>false,at:()=>[],kt:()=>({}),Pe:{state:{}},yn:{},Ne:()=>'',Y:()=>'',Rt:()=>({}),U:()=> 'Scout',ee:x=>x,wi:()=>false,We:x=>x,Dt:()=>false,q:jsx,ot:jsx,botsModLifecycleCss:'',an:()=>true,botsModArchiveEffect:f=>f(),botsModBindArchive:(_bot,r)=>{archiveRows=r},botsModIsSelected:()=>false,botsModSessionLabel:r=>r.title,botsModSessionLastActive:()=>''};
for(const name of ['mu','fu','nr','Gn','pu','_n','ji','pc','je','ho','Gp','Pp'])ctx[name]=name;
vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('function botsModInternalToggle'),source.indexOf('function botsModIsInternalSession'))+helpers+'\n'+render,ctx);
function flatten(node){if(!node||typeof node!=='object')return [];return [node,...(Array.isArray(node.children)?node.children:[node.children]).flatMap(flatten)];}
function draw(){return flatten(ctx.hc({bot:{name:'scout'}}));}
let tree=draw();
assert.equal(tree.filter(n=>n.className==='bots-mod-session-row group row-hover relative').length,1);
assert.equal(archiveRows.length,1,'Archive successors must exclude hidden internal chats');
assert.ok(!tree.some(n=>n.children==='Bot Chat'));
const toggle=()=>ctx.botsModInternalToggle().children;
assert.equal(toggle()['aria-label'],'Show internal chats');
assert.ok(!tree.some(n=>String(n.children).startsWith('Show internal chats')));
toggle().onClick();
tree=draw();assert.ok(tree.some(n=>n.children==='Bot Chat'));assert.equal(archiveRows.length,2);
assert.equal(toggle()['aria-pressed'],true);toggle().onClick();assert.equal(show,false);
rows=[rows[0]];tree=draw();assert.ok(!tree.some(n=>n.className==='bots-mod-session-row group row-hover relative'));
assert.ok(!tree.some(n=>n.children==='No sessions yet'));
assert.ok(tree.some(n=>n.children==='Open internal activity'));
assert.equal(ctx.botsModIsInternalSession({title:'Bot Chat planning'}),false);
assert.equal(rows[0].title,'Bot Chat','Canonical title unchanged');
assert.equal(tree[0]['data-bots-compact'],'true','Internal-only bot compacts');
assert.equal(tree.find(n=>n.type==='je').size,30,'Compact avatars must be enlarged');
toggle().onClick();
assert.equal(draw()[0]['data-bots-compact'],'false','Revealing internal chats expands bot');
show=false;rows=[];
assert.equal(draw()[0]['data-bots-compact'],'true','Empty bot compacts');
rows=[{id:'user',title:'User task'}];
assert.equal(draw()[0]['data-bots-compact'],'false','User chats stay full width');
assert.equal(draw().find(n=>n.type==='je').size,30,'Inline bot avatars match tile avatars');
ctx.rc=()=>({data:[],isLoading:true});
assert.equal(draw()[0]['data-bots-compact'],'false','Loading is not treated as empty');
ctx.rc=()=>({data:[],isError:true});
assert.equal(draw()[0]['data-bots-compact'],'false','Errors are not treated as empty');
console.log('PASS: compact layout eligibility and automatic expansion.');
console.log('PASS: actual roster component hides internal rows, toggles both ways, preserves access and titles, avoids empty placeholders, and excludes hidden rows from archive successors.');
